// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/mail.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MailMessage represents a simplified email message
type MailMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient     string                 `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailMessage) Reset() {
	*x = MailMessage{}
	mi := &file_proto_mail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailMessage) ProtoMessage() {}

func (x *MailMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailMessage.ProtoReflect.Descriptor instead.
func (*MailMessage) Descriptor() ([]byte, []int) {
	return file_proto_mail_proto_rawDescGZIP(), []int{0}
}

func (x *MailMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MailMessage) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *MailMessage) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *MailMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *MailMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type RegisterMailboxRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Username       string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	MailboxAddress string                 `protobuf:"bytes,2,opt,name=mailbox_address,json=mailboxAddress,proto3" json:"mailbox_address,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterMailboxRequest) Reset() {
	*x = RegisterMailboxRequest{}
	mi := &file_proto_mail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMailboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMailboxRequest) ProtoMessage() {}

func (x *RegisterMailboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMailboxRequest.ProtoReflect.Descriptor instead.
func (*RegisterMailboxRequest) Descriptor() ([]byte, []int) {
	return file_proto_mail_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterMailboxRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterMailboxRequest) GetMailboxAddress() string {
	if x != nil {
		return x.MailboxAddress
	}
	return ""
}

type RegisterMailboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMailboxResponse) Reset() {
	*x = RegisterMailboxResponse{}
	mi := &file_proto_mail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMailboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMailboxResponse) ProtoMessage() {}

func (x *RegisterMailboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMailboxResponse.ProtoReflect.Descriptor instead.
func (*RegisterMailboxResponse) Descriptor() ([]byte, []int) {
	return file_proto_mail_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterMailboxResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterMailboxResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LookupMailboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupMailboxRequest) Reset() {
	*x = LookupMailboxRequest{}
	mi := &file_proto_mail_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupMailboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupMailboxRequest) ProtoMessage() {}

func (x *LookupMailboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupMailboxRequest.ProtoReflect.Descriptor instead.
func (*LookupMailboxRequest) Descriptor() ([]byte, []int) {
	return file_proto_mail_proto_rawDescGZIP(), []int{3}
}

func (x *LookupMailboxRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type LookupMailboxResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MailboxAddress string                 `protobuf:"bytes,1,opt,name=mailbox_address,json=mailboxAddress,proto3" json:"mailbox_address,omitempty"`
	Found          bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LookupMailboxResponse) Reset() {
	*x = LookupMailboxResponse{}
	mi := &file_proto_mail_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupMailboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupMailboxResponse) ProtoMessage() {}

func (x *LookupMailboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupMailboxResponse.ProtoReflect.Descriptor instead.
func (*LookupMailboxResponse) Descriptor() ([]byte, []int) {
	return file_proto_mail_proto_rawDescGZIP(), []int{4}
}

func (x *LookupMailboxResponse) GetMailboxAddress() string {
	if x != nil {
		return x.MailboxAddress
	}
	return ""
}

func (x *LookupMailboxResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type ReceiveMailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *MailMessage           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveMailRequest) Reset() {
	*x = ReceiveMailRequest{}
	mi := &file_proto_mail_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveMailRequest) ProtoMessage() {}

func (x *ReceiveMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveMailRequest.ProtoReflect.Descriptor instead.
func (*ReceiveMailRequest) Descriptor() ([]byte, []int) {
	return file_proto_mail_proto_rawDescGZIP(), []int{5}
}

func (x *ReceiveMailRequest) GetMessage() *MailMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type ReceiveMailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveMailResponse) Reset() {
	*x = ReceiveMailResponse{}
	mi := &file_proto_mail_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveMailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveMailResponse) ProtoMessage() {}

func (x *ReceiveMailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveMailResponse.ProtoReflect.Descriptor instead.
func (*ReceiveMailResponse) Descriptor() ([]byte, []int) {
	return file_proto_mail_proto_rawDescGZIP(), []int{6}
}

func (x *ReceiveMailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReceiveMailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetMailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMailRequest) Reset() {
	*x = GetMailRequest{}
	mi := &file_proto_mail_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMailRequest) ProtoMessage() {}

func (x *GetMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMailRequest.ProtoReflect.Descriptor instead.
func (*GetMailRequest) Descriptor() ([]byte, []int) {
	return file_proto_mail_proto_rawDescGZIP(), []int{7}
}

func (x *GetMailRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetMailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*MailMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMailResponse) Reset() {
	*x = GetMailResponse{}
	mi := &file_proto_mail_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMailResponse) ProtoMessage() {}

func (x *GetMailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMailResponse.ProtoReflect.Descriptor instead.
func (*GetMailResponse) Descriptor() ([]byte, []int) {
	return file_proto_mail_proto_rawDescGZIP(), []int{8}
}

func (x *GetMailResponse) GetMessages() []*MailMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type SendMailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *MailMessage           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMailRequest) Reset() {
	*x = SendMailRequest{}
	mi := &file_proto_mail_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMailRequest) ProtoMessage() {}

func (x *SendMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMailRequest.ProtoReflect.Descriptor instead.
func (*SendMailRequest) Descriptor() ([]byte, []int) {
	return file_proto_mail_proto_rawDescGZIP(), []int{9}
}

func (x *SendMailRequest) GetMessage() *MailMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type SendMailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMailResponse) Reset() {
	*x = SendMailResponse{}
	mi := &file_proto_mail_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMailResponse) ProtoMessage() {}

func (x *SendMailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mail_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMailResponse.ProtoReflect.Descriptor instead.
func (*SendMailResponse) Descriptor() ([]byte, []int) {
	return file_proto_mail_proto_rawDescGZIP(), []int{10}
}

func (x *SendMailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendMailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_mail_proto protoreflect.FileDescriptor

const file_proto_mail_proto_rawDesc = "" +
	"\n" +
	"\x10proto/mail.proto\x12\x04mail\"\x8f\x01\n" +
	"\vMailMessage\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\tR\trecipient\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"]\n" +
	"\x16RegisterMailboxRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12'\n" +
	"\x0fmailbox_address\x18\x02 \x01(\tR\x0emailboxAddress\"M\n" +
	"\x17RegisterMailboxResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"2\n" +
	"\x14LookupMailboxRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"V\n" +
	"\x15LookupMailboxResponse\x12'\n" +
	"\x0fmailbox_address\x18\x01 \x01(\tR\x0emailboxAddress\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"A\n" +
	"\x12ReceiveMailRequest\x12+\n" +
	"\amessage\x18\x01 \x01(\v2\x11.mail.MailMessageR\amessage\"I\n" +
	"\x13ReceiveMailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x0eGetMailRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"@\n" +
	"\x0fGetMailResponse\x12-\n" +
	"\bmessages\x18\x01 \x03(\v2\x11.mail.MailMessageR\bmessages\">\n" +
	"\x0fSendMailRequest\x12+\n" +
	"\amessage\x18\x01 \x01(\v2\x11.mail.MailMessageR\amessage\"F\n" +
	"\x10SendMailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xa6\x01\n" +
	"\n" +
	"Nameserver\x12N\n" +
	"\x0fRegisterMailbox\x12\x1c.mail.RegisterMailboxRequest\x1a\x1d.mail.RegisterMailboxResponse\x12H\n" +
	"\rLookupMailbox\x12\x1a.mail.LookupMailboxRequest\x1a\x1b.mail.LookupMailboxResponse2\x85\x01\n" +
	"\aMailbox\x12B\n" +
	"\vReceiveMail\x12\x18.mail.ReceiveMailRequest\x1a\x19.mail.ReceiveMailResponse\x126\n" +
	"\aGetMail\x12\x14.mail.GetMailRequest\x1a\x15.mail.GetMailResponse2K\n" +
	"\x0eTransferServer\x129\n" +
	"\bSendMail\x12\x15.mail.SendMailRequest\x1a\x16.mail.SendMailResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_mail_proto_rawDescOnce sync.Once
	file_proto_mail_proto_rawDescData []byte
)

func file_proto_mail_proto_rawDescGZIP() []byte {
	file_proto_mail_proto_rawDescOnce.Do(func() {
		file_proto_mail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mail_proto_rawDesc), len(file_proto_mail_proto_rawDesc)))
	})
	return file_proto_mail_proto_rawDescData
}

var file_proto_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_mail_proto_goTypes = []any{
	(*MailMessage)(nil),             // 0: mail.MailMessage
	(*RegisterMailboxRequest)(nil),  // 1: mail.RegisterMailboxRequest
	(*RegisterMailboxResponse)(nil), // 2: mail.RegisterMailboxResponse
	(*LookupMailboxRequest)(nil),    // 3: mail.LookupMailboxRequest
	(*LookupMailboxResponse)(nil),   // 4: mail.LookupMailboxResponse
	(*ReceiveMailRequest)(nil),      // 5: mail.ReceiveMailRequest
	(*ReceiveMailResponse)(nil),     // 6: mail.ReceiveMailResponse
	(*GetMailRequest)(nil),          // 7: mail.GetMailRequest
	(*GetMailResponse)(nil),         // 8: mail.GetMailResponse
	(*SendMailRequest)(nil),         // 9: mail.SendMailRequest
	(*SendMailResponse)(nil),        // 10: mail.SendMailResponse
}
var file_proto_mail_proto_depIdxs = []int32{
	0,  // 0: mail.ReceiveMailRequest.message:type_name -> mail.MailMessage
	0,  // 1: mail.GetMailResponse.messages:type_name -> mail.MailMessage
	0,  // 2: mail.SendMailRequest.message:type_name -> mail.MailMessage
	1,  // 3: mail.Nameserver.RegisterMailbox:input_type -> mail.RegisterMailboxRequest
	3,  // 4: mail.Nameserver.LookupMailbox:input_type -> mail.LookupMailboxRequest
	5,  // 5: mail.Mailbox.ReceiveMail:input_type -> mail.ReceiveMailRequest
	7,  // 6: mail.Mailbox.GetMail:input_type -> mail.GetMailRequest
	9,  // 7: mail.TransferServer.SendMail:input_type -> mail.SendMailRequest
	2,  // 8: mail.Nameserver.RegisterMailbox:output_type -> mail.RegisterMailboxResponse
	4,  // 9: mail.Nameserver.LookupMailbox:output_type -> mail.LookupMailboxResponse
	6,  // 10: mail.Mailbox.ReceiveMail:output_type -> mail.ReceiveMailResponse
	8,  // 11: mail.Mailbox.GetMail:output_type -> mail.GetMailResponse
	10, // 12: mail.TransferServer.SendMail:output_type -> mail.SendMailResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_mail_proto_init() }
func file_proto_mail_proto_init() {
	if File_proto_mail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mail_proto_rawDesc), len(file_proto_mail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_mail_proto_goTypes,
		DependencyIndexes: file_proto_mail_proto_depIdxs,
		MessageInfos:      file_proto_mail_proto_msgTypes,
	}.Build()
	File_proto_mail_proto = out.File
	file_proto_mail_proto_goTypes = nil
	file_proto_mail_proto_depIdxs = nil
}
